### ISSUE TITLE
potential java-issue on big sur

### ISSUE THREAD

**Issue by chinatsu** [chinatsu/c2lina#5]
it appears running `/usr/libexec/java_home -v 1.6` on a relatively fresh install of big sur outputs
```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com/ for information on installing Java.
```
even though java 1.6 is installed.

a workaround for now is to replace ` $(/usr/libexec/java_home -v 1.6)/bin/java` with
`/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java` in run.sh, that should make it possible to run the game on big sur.

**Comment by zDEFz** [comment]
are you sure your `/Library/Java/JavaVirtualMachines/1.6.0.jdk/` isn't empty? I have found running the script fresh just skips installation of that...

I also observed that the general behavior of sh seems different. Your script used to work, now mkdir gets `read-only filesystem` as error.

I think that we might need to create a `.plist` file.

You can try  `launchctl setenv JAVA_HOME <yourpath>`

But so far, I haven't had the proper thing, cause `which java` still returns the same.


If it would work, you would create the .plist file under `~/Library/LaunchAgents `
it would look something like this:
https://hastebin.com/qaneqevuza.xml

**Comment by zDEFz** [comment]
But looking back, the workaround seems easier to implement :)

**Comment by chinatsu** [comment]
so, your theory here is that a populated folder at the path where 1.6 gets installed prevents the system to detect any java runtime? 

`/usr/libexec/java_home` should warn with something like `Unable to find any JVMs matching version "1.6".`. the reported error seems to imply there is not a single java runtime to be found after an update to big sur

**Comment by chinatsu** [comment]
will create a new issue if someone encounters other problems related to this
